# bot.conf
# Configuration file for the Millimobile bot. Add this 
# to the "extra Kconfig fragments" option in the build configuration

# Select the bot profile from Kconfig
CONFIG_MILLIMOBILE_BOT=y

# Disable the serial console to achieve low power
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n

# If you need logging set the config below
# to enable (=y) RTT communication
CONFIG_RTT=n
