# bot.conf

# Select the bot profile from Kconfig
CONFIG_MILLIMOBILE_BOT=y

# Disable the serial console to achieve low power
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n

# If you need logging uncomment the config below
# to enable RTT communication
CONFIG_RTT=y
