
CONFIG_GPIO=y

CONFIG_BT=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_PER_ADV=y
CONFIG_BT_EXT_ADV=y
CONFIG_BT_PER_ADV_SYNC=y
CONFIG_BT_DEVICE_NAME="MilliMobile"

CONFIG_BT_MAX_CONN=1
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER=y
CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER=y

CONFIG_BT_PER_ADV_RSP=y
CONFIG_BT_PER_ADV_SYNC_RSP=y
CONFIG_BT_PER_ADV_SYNC_BUF_SIZE=247

CONFIG_BT_REMOTE_INFO=y
CONFIG_BT_GATT_CLIENT=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y

CONFIG_MILLIMOBILE_MODE_SWITCHING=y
CONFIG_MILLIMOBILE_ADV=y
CONFIG_MILLIMOBILE_SYNC=y
CONFIG_MILLIMOBILE_CMD=y

CONFIG_I2C=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_TFM_SECURE_UART=n
CONFIG_TFM_LOG_LEVEL_SILENCE=y

CONFIG_CBPRINTF_FP_SUPPORT=y
